"""Adversarial text modes for VLM faithfulness evaluation.

The natural Markov text we generate looks plausibly English, which means a
VLM can score highly by leaning on its language prior instead of reading the
pixels. These modes strip the prior to varying degrees so you can measure the
gap.

Public entry point: `transform(text, mode)`. The `VALID_MODES` tuple lists
every accepted `mode` string.
"""

from __future__ import annotations

from .brands import (
    _AUTHORS,
    _BRAND_SWAPS,
    _LOOKALIKE_DRUGS,
    _MIXED_CASE_BRANDS,
    brand_swap_text,
    citation_format_text,
    lookalike_drugs_text,
    mixed_case_brand_text,
)
from .case import (
    all_caps_mid_sentence_text,
    all_caps_text,
    mixed_case_text,
    punct_storm_text,
    repeat_chars_text,
)
from .core import (
    _LANG_ALPHABETS,
    _LANG_DICTS,
    _TYPO_OPS,
    VALID_MODES,
    _esc_xml,
    _load_wordset,
    _mutate_word,
    _typo_lang,
    set_typo_lang,
)
from .dispatch import transform
from .glyph import (
    _CONFUSABLES,
    _DIGIT_SWAPS,
    _HOMOGLYPHS,
    _LEET_MAP,
    confusables_text,
    digit_heavy_text,
    homoglyph_text,
    leetspeak_text,
)
from .markup import (
    _BULLET_GLYPHS,
    _CODE_FRAGMENTS,
    bullet_markers_text,
    code_block_text,
    highlighted_text,
    italic_emphasis_text,
    strikethrough_emphasis_text,
    strikethrough_text,
    whitespace_tabs_text,
    wide_kerning_text,
)
from .multilingual import (
    _CODE_SWITCH_PHRASES,
    _EMAIL_DOMAIN,
    _EMAIL_LOCAL,
    _URL_HOSTS,
    _URL_PATHS,
    code_switching_text,
    emails_text,
    long_urls_text,
    stutter_text,
)
from .numbers import (
    _ID_TEMPLATES,
    _MONTHS,
    _MONTHS_FULL,
    _POSTAL_FORMATS,
    _RARE_CURRENCY_SYMBOLS,
    _ROMAN_VALUES,
    date_formats_text,
    leading_zeros_text,
    locale_numbers_text,
    postal_codes_text,
    precision_numbers_text,
    rare_currency_text,
    roman_numerals_text,
    structured_ids_text,
    to_roman,
)
from .phrases import (
    _CRITICAL_NOT_SENTENCES,
    _FACTUAL_SWAPS,
    _FAMOUS_SWAPS,
    _HOMOPHONE_TRAPS,
    _TYPO_EXPLAINED_SENTENCES,
    critical_not_paragraph,
    factual_swap_paragraph,
    famous_swap_paragraph,
    homophone_trap_paragraph,
    typo_explained_paragraph,
)
from .pseudo import _gibberish_word, _pseudo_word_of_length
from .scramble import scramble_text
from .typos import (
    bold_typos_text,
    diverse_typos_text,
    hyphenation_breaks_text,
)
from .unicode_chars import (
    _BIDI_PHRASES,
    _FOREIGN_NAMES,
    _GREEK_USAGES,
    _GREEK_VARS,
    _MIXED_NAMES,
    _MOJIBAKE_PHRASES,
    _SCIENTIFIC_SYMBOLS,
    _SUPERSCRIPT_DIGITS,
    bidi_text_mode,
    footnote_markers_text,
    foreign_names_text,
    greek_variables_text,
    mixed_script_word_text,
    mojibake_text,
    scientific_symbols_text,
)

__all__ = [
    "VALID_MODES",
    "transform",
    "set_typo_lang",
    # per-mode transforms (kept for direct callers and tests)
    "scramble_text",
    "confusables_text",
    "digit_heavy_text",
    "homoglyph_text",
    "leetspeak_text",
    "all_caps_text",
    "all_caps_mid_sentence_text",
    "mixed_case_text",
    "repeat_chars_text",
    "punct_storm_text",
    "diverse_typos_text",
    "bold_typos_text",
    "hyphenation_breaks_text",
    "brand_swap_text",
    "mixed_case_brand_text",
    "lookalike_drugs_text",
    "citation_format_text",
    "leading_zeros_text",
    "precision_numbers_text",
    "roman_numerals_text",
    "to_roman",
    "locale_numbers_text",
    "structured_ids_text",
    "date_formats_text",
    "postal_codes_text",
    "rare_currency_text",
    "foreign_names_text",
    "scientific_symbols_text",
    "greek_variables_text",
    "bidi_text_mode",
    "mixed_script_word_text",
    "footnote_markers_text",
    "mojibake_text",
    "strikethrough_text",
    "strikethrough_emphasis_text",
    "italic_emphasis_text",
    "highlighted_text",
    "wide_kerning_text",
    "bullet_markers_text",
    "code_block_text",
    "whitespace_tabs_text",
    "code_switching_text",
    "stutter_text",
    "long_urls_text",
    "emails_text",
    "famous_swap_paragraph",
    "homophone_trap_paragraph",
    "critical_not_paragraph",
    "factual_swap_paragraph",
    "typo_explained_paragraph",
    # private pools / helpers re-exported for scripts/ scorers
    "_AUTHORS",
    "_BIDI_PHRASES",
    "_BRAND_SWAPS",
    "_BULLET_GLYPHS",
    "_CODE_FRAGMENTS",
    "_CODE_SWITCH_PHRASES",
    "_CONFUSABLES",
    "_CRITICAL_NOT_SENTENCES",
    "_DIGIT_SWAPS",
    "_EMAIL_DOMAIN",
    "_EMAIL_LOCAL",
    "_FACTUAL_SWAPS",
    "_FAMOUS_SWAPS",
    "_FOREIGN_NAMES",
    "_GREEK_USAGES",
    "_GREEK_VARS",
    "_HOMOGLYPHS",
    "_HOMOPHONE_TRAPS",
    "_ID_TEMPLATES",
    "_LANG_ALPHABETS",
    "_LANG_DICTS",
    "_LEET_MAP",
    "_LOOKALIKE_DRUGS",
    "_MIXED_CASE_BRANDS",
    "_MIXED_NAMES",
    "_MOJIBAKE_PHRASES",
    "_MONTHS",
    "_MONTHS_FULL",
    "_POSTAL_FORMATS",
    "_RARE_CURRENCY_SYMBOLS",
    "_ROMAN_VALUES",
    "_SCIENTIFIC_SYMBOLS",
    "_SUPERSCRIPT_DIGITS",
    "_TYPO_EXPLAINED_SENTENCES",
    "_TYPO_OPS",
    "_URL_HOSTS",
    "_URL_PATHS",
    "_esc_xml",
    "_gibberish_word",
    "_load_wordset",
    "_mutate_word",
    "_pseudo_word_of_length",
    "_typo_lang",
]
