"""Markov-based text generator (prose, headings, code, lists, …).

Public entry point for ``from docduck.generators import text``. The
package layout splits implementation across ``models`` (Markov loading,
language/genre selection), ``modes`` (adversarial content mode),
``sentences`` (sentence-/paragraph-level generation, inline markup) and
``structured`` (lists, definitions, footnotes, tables, code snippets).

Re-exports preserve the legacy ``text_gen`` namespace so callers that
``import text as text_gen`` keep working unchanged. Underscore-prefixed
helpers are part of that contract (tests and other internal modules
reach for them directly) and so they are explicitly re-exported here.
"""

from .models import (
    _CORPORA_DIR,
    _SCRIPT_RETRY_TRIES,
    ENGLISH_GENRES,
    MULTILINGUAL_CODES,
    _accept_sample,
    _load_model,
    _locked_genre,
    _models,
    _pick_model,
    available_languages,
    available_models,
    english_genres,
    get_locked_genre,
    set_locked_genre,
)
from .modes import (
    _apply_mode,
    _content_mode,
    get_content_mode,
    set_content_mode,
)
from .sentences import (
    _ADJECTIVES,
    _ADVERBS,
    _CONJUNCTIONS,
    _DETERMINERS,
    _NOUNS,
    _PREPOSITIONS,
    _SENTENCE_PATTERNS,
    _VERBS,
    _add_inline_markup,
    _escape_xml,
    _make_sentence,
    _markov_sentence,
    _markov_short,
    _normalize_spacing,
    _template_sentence,
    gen_heading,
    gen_paragraph,
    gen_paragraphs,
    gen_title,
)
from .sources import (
    TextSource,
    get_text_source,
    register_text_source,
    reset_text_source,
    set_text_source,
)
from .structured import (
    _gen_bash_snippet,
    _gen_c_snippet,
    _gen_go_snippet,
    _gen_javascript_snippet,
    _gen_python_snippet,
    _gen_rust_snippet,
    _gen_sql_snippet,
    _rand_func,
    _rand_type,
    _rand_var,
    gen_blockquote,
    gen_code_snippet,
    gen_definition_items,
    gen_footnotes,
    gen_list_items,
    gen_table_data,
)

__all__ = [
    # ---- Public API -----------------------------------------------------
    "ENGLISH_GENRES",
    "MULTILINGUAL_CODES",
    "available_languages",
    "available_models",
    "english_genres",
    "get_content_mode",
    "get_locked_genre",
    "set_content_mode",
    "TextSource",
    "get_text_source",
    "register_text_source",
    "reset_text_source",
    "set_text_source",
    "set_locked_genre",
    "gen_blockquote",
    "gen_code_snippet",
    "gen_definition_items",
    "gen_footnotes",
    "gen_heading",
    "gen_list_items",
    "gen_paragraph",
    "gen_paragraphs",
    "gen_table_data",
    "gen_title",
    # ---- Underscore-prefixed helpers used by other modules / tests -----
    "_CORPORA_DIR",
    "_SCRIPT_RETRY_TRIES",
    "_accept_sample",
    "_load_model",
    "_locked_genre",
    "_models",
    "_pick_model",
    "_apply_mode",
    "_content_mode",
    "_ADJECTIVES",
    "_ADVERBS",
    "_CONJUNCTIONS",
    "_DETERMINERS",
    "_NOUNS",
    "_PREPOSITIONS",
    "_SENTENCE_PATTERNS",
    "_VERBS",
    "_add_inline_markup",
    "_escape_xml",
    "_make_sentence",
    "_markov_sentence",
    "_markov_short",
    "_normalize_spacing",
    "_template_sentence",
    "_gen_bash_snippet",
    "_gen_c_snippet",
    "_gen_go_snippet",
    "_gen_javascript_snippet",
    "_gen_python_snippet",
    "_gen_rust_snippet",
    "_gen_sql_snippet",
    "_rand_func",
    "_rand_type",
    "_rand_var",
]
